# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amux < Formula
  desc "Manage parallel AI agent workspaces with git"
  homepage "https://github.com/brianaffirm/amux"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brianaffirm/amux/releases/download/v0.1.0/amux_0.1.0_darwin_amd64.tar.gz"
      sha256 "ba18c4916d9e4bdb2c38945c52c131b35b94bc6118dec92a1a578952edfae7bc"

      define_method(:install) do
        bin.install "amux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brianaffirm/amux/releases/download/v0.1.0/amux_0.1.0_darwin_arm64.tar.gz"
      sha256 "8a180404ebf39717445dcecd7948adb9039daf2dfee8ac2881c8c96e7b879cd0"

      define_method(:install) do
        bin.install "amux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brianaffirm/amux/releases/download/v0.1.0/amux_0.1.0_linux_amd64.tar.gz"
      sha256 "5f71a58295de8af79dd758bf9d1c8650691b7c6cbe71cd0563403e1078ad131f"
      define_method(:install) do
        bin.install "amux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brianaffirm/amux/releases/download/v0.1.0/amux_0.1.0_linux_arm64.tar.gz"
      sha256 "ee2581d13b074d41300bdf4ceeaf4edb95a9217f89066069cc23e0505a752d64"
      define_method(:install) do
        bin.install "amux"
      end
    end
  end

  test do
    assert_match "amux", shell_output("#{bin}/amux --help")
  end
end
